version: '3.2'
services:
  slackinvite:
    command: '${SLACK_SUBDOMAIN} ${SLACK_API_TOKEN} ${GOOGLE_CAPTCHA_SECRET} ${GOOGLE_CAPTCHA_SITEKEY}'
    image: opencadc/slackin
    ports:
      - '3000:3000'
    environment:
      - SLACK_INTERVAL=${SLACK_INTERVAL-10000}
